//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCOLPROYECTOS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerPro
    {
        public int id { get; set; }
        public Nullable<int> idServicio { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public int idCliente { get; set; }
        public int idEstadoSP { get; set; }
        public int idCiudad { get; set; }
        public int idRecursoT { get; set; }
        public int idLineaT { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoSerPro EstadoSerPro { get; set; }
        public virtual LineaTrabajo LineaTrabajo { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual RecursoTecnico RecursoTecnico { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
