//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCOLPROYECTOS_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.SerPro = new HashSet<SerPro>();
        }
    
        public int id { get; set; }
        public string codigoServicio { get; set; }
        public string nombreServicio { get; set; }
        public System.DateTime fechaServicio { get; set; }
        public int valorServicio { get; set; }
        public string lineaServicio { get; set; }
        public int idUsuarioSer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerPro> SerPro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
